language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
script:
  - npm run build

deploy:
  provider: pages
  skip_cleanup: true
  keep_history: true
  github_token: 539a7dc761d882f0cefe0af3b20a5af9edb38c54
  target-branch: gh-pages
  local-dir: build
  on:
    branch: master